// Banco de dados dos produtos

const data = [{
    id: 1,
    img: "../img/sem título (técnica mista).jpg",
    nameItem: "Aura de emoções",
    description: "A energia que sentimos, que nós mesmo emitimos!",
    value: 150,
    addCart: "Adicionar ao carrinho",
    tag: ["À Lápis"],
  },
  {
    id: 2,
    img: "../img/eu pertenço ao hoje.jpg",
    nameItem: "Eu pertenço ao hoje",
    description: "Aproveitar o presente, pois o nome presente não é à toa!",
    value: 125,
    addCart: "Adicionar ao carrinho",
    tag: ["À Lápis", "Mista"],
  },
  {
    id: 3,
    img: "../img/gravura 1.jpg",
    nameItem: "Gravura",
    description: "Uma simples representação!",
    value: 100,
    addCart: "Adicionar ao carrinho",
    tag: ["À Tinta"],
  },
  {
    id: 4,
    img: "../img/imersão.jpg",
    nameItem: "Imersão",
    description: "É como entrar em uma nova realizada, como entrar numa mata sem volta!",
    value: 220,
    addCart: "Adicionar ao carrinho",
    tag: ["À Tinta", "Mista"],
  },
  {
    id: 5,
    img: "../img/mulheres são sementes.jpg",
    nameItem: "Mulheres são sementes",
    description: "O cultivo é feito com amor!",
    value: 130,
    addCart: "Adicionar ao carrinho",
    tag: ["À Lápis"],
  },
  {
    id: 6,
    img: "../img/O mistério da flor.jpg",
    nameItem: "O mistério da flor",
    description: "O que dizer.....",
    value: 250,
    addCart: "Adicionar ao carrinho",
    tag: ["À Lápis"],
  },
];